[workspace]
members = []
[package]
name = "pyrrhic-rs"
authors = ["Algorhythm"]
version = "0.1.0"
publish = false
edition = "2021"
autobins = false

[lib]
name = "pyrrhic_rs"
crate-type = ["staticlib", "rlib"]
[dependencies]
cozy-chess = "0.3.3"
libc = "0.2"

